Algoritmo "lesson1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/06/2023
Var
// Seção de Declarações das variáveis 

      note: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

         note <- 100
         escreva("Result:", note)

Fimalgoritmo